site_name: Waffles
site_url: 'https://wffls.github.io'
site_description: 'Simple Configuration Tools'
repo_url: 'https://github.com/wffls'
remote_branch: 'master'
theme: 'readthedocs'
google_analytics: ['UA-75603-16', 'wffls.github.io']

markdown_extensions:
  - admonition

pages:
  - Home: 'index.md'
  - Guides:
    - Install Waffles: 'guides/install_waffles.md'
    - Install wafflescript: 'guides/install_wafflescript.md'
  - Functions:
    - arrays: 'functions/arrays.md'
    - consul: 'functions/consul.md'
    - exec: 'functions/exec.md'
    - ini: 'functions/ini.md'
    - logging: 'functions/logging.md'
    - mysql: 'functions/mysql.md'
    - options: 'functions/options.md'
    - resource: 'functions/resource.md'
    - strings: 'functions/strings.md'
    - utils: 'functions/utils.md'
  - Waffles Resources:
    - apt.key: 'resources/apt.key.md'
    - apt.pkg: 'resources/apt.pkg.md'
    - apt.ppa: 'resources/apt.ppa.md'
    - apt.source: 'resources/apt.source.md'
    - augeas.generic: 'resources/augeas.generic.md'
    - consul.check: 'resources/consul.check.md'
    - consul.service: 'resources/consul.service.md'
    - consul.template: 'resources/consul.template.md'
    - consul.watch: 'resources/consul.watch.md'
    - cron.entry: 'resources/cron.entry.md'
    - dnf.copr: 'resources/dnf.copr.md'
    - dnf.pkg: 'resources/dnf.pkg.md'
    - dnf.repo: 'resources/dnf.repo.md'
    - dpkg.debconf: 'resources/dpkg.debconf.md'
    - file.ini: 'resources/file.ini.md'
    - file.line: 'resources/file.line.md'
    - git.repo: 'resources/git.repo.md'
    - ip6tables.rule: 'resources/ip6tables.rule.md'
    - iptables.rule: 'resources/iptables.rule.md'
    - mysql.database: 'resources/mysql.database.md'
    - mysql.grant: 'resources/mysql.grant.md'
    - mysql.user: 'resources/mysql.user.md'
    - os.directory: 'resources/os.directory.md'
    - os.file: 'resources/os.file.md'
    - os.groupadd: 'resources/os.groupadd.md'
    - os.symlink: 'resources/os.symlink.md'
    - os.useradd: 'resources/os.useradd.md'
    - python.pip: 'resources/python.pip.md'
    - python.virtualenv: 'resources/python.virtualenv.md'
    - rabbitmq.policy: 'resources/rabbitmq.policy.md'
    - rabbitmq.user_permissions: 'resources/rabbitmq.user_permissions.md'
    - rabbitmq.user: 'resources/rabbitmq.user.md'
    - rabbitmq.vhost: 'resources/rabbitmq.vhost.md'
    - ruby.gem: 'resources/ruby.gem.md'
    - service.sysv: 'resources/service.sysv.md'
    - service.upstart: 'resources/service.upstart.md'
    - sudoers.cmd: 'resources/sudoers.cmd.md'
